name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


env:
  RLM_LICENSE: 5053@104.46.46.229


jobs:

  processing:
    runs-on: ubuntu-latest
    container: ghcr.io/anybody/anybodycon-linux:7.3.4-1

    steps:
      - uses: actions/checkout@v2

      - name: Run AnyBody using wine
        env:
          RLM_LICENSE_PASSWORD: ${{ secrets.LICENSE_PASSWORD }}
        run: wine ".wine/drive_c/Program Files/AnyBody Technology/AnyBody.7.3/AnyBodyCon.exe" /ni

      - name: test AnyBody python
        env:
          RLM_LICENSE_PASSWORD: ${{ secrets.LICENSE_PASSWORD }}
        shell: python
        run: |
          import anypytools
          print(anypytools.tools.anybodycon_version())
