name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: 0 3 * * 6

jobs:
  processing:
    runs-on: ${{ matrix.runs-on }}
    container: ghcr.io/anybody/anybodycon-linux-github-actions:latest
    env:
      RLM_LICENSE_PASSWORD: ${{ secrets.LICENSE_TEST_SERVER_PASSWORD }}
      RLM_LICENSE: ${{ secrets.LICENSE_TEST_SERVER }}

    strategy:
      matrix: 
        runs-on: [ubuntu-latest, self-hosted]

    steps:     
      - uses: actions/checkout@v3

      - name: Run AnyBodyCon directly
        run: |
          anybodycon /ni
          # python processing-script.py 

      - name: Run processing with Python
        shell: python
        run: |
          import anypytools 
          app = anypytools.AnyPyProcess()
          macro = [
            'load "knee.main.any"',
            'operation Main.MyStudy.InverseDynamics',
            'run',
            'classoperation Main.MyStudy.Output.Abscissa.t "Dump"',
            'classoperation Main.MyStudy.Output.MomentArm "Dump"',
          ]
          results = app.start_macro(macro)
          
          df = results.to_dataframe()
          df.to_pickle("result.pkl.bz2")

      - uses: actions/upload-artifact@v2
        with:
          name: Processing results
          path: result.pkl.bz2
