name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  processing:
    runs-on: ubuntu-latest
    container: ghcr.io/anybody/anybodycon-linux:7.4.4-0

    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run AnyBody using wine
        run: wine .wine/drive_c/Program Files/AnyBody Technology/AnyBody.7.3/AnyBodyCon.exe /ni

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
